{
 "title": "Stats",
 "time": { "from": "2015-06-25T05:31:21.363Z", "to": "2023-11-03T21:05:32.976Z" },
 "panels": [
  {
   "title": "History",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  master_metadata_album_artist_name as \"Artist\",\n  master_metadata_track_name as \"Track\"\nFROM spotify_table\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Listening history",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  id\nFROM spotify_table\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Favourite Artists",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT master_metadata_album_artist_name, COUNT(*) AS occurrences\nFROM spotify_table\nWHERE\n  $__timeFilter(ts)\nGROUP BY master_metadata_album_artist_name\nORDER BY occurrences desc;"
    }
   ]
  },
  {
   "title": "Favourite Tracks",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT master_metadata_track_name as \"Track\", COUNT(*) AS occurrences\nFROM spotify_table\nWHERE\n  $__timeFilter(ts)\nGROUP BY master_metadata_track_name\nORDER BY occurrences desc;"
    }
   ]
  }
 ]
}